### ISSUE TITLE
[enhancement] Add functionality for tags

### ISSUE THREAD

**Issue by Maikeleg** [devWaves/SwitchBot-MQTT-BLE-ESP32#100]
Switchbot now also sells tags, Bluetooth beacons 
Would it be possible to add these as a device?
Im happy to test them and test code-alterations 
Im not sure if I’m allowed to put this request here, if not please instruct me how

**Comment by devWaves** [comment]
if you mean the NFC tags, those can't be supported. They don't use bluetooth. They use the NFC reader on your phone to talk to the switchbot app. There is no battery in the tag https://ca.switch-bot.com/products/switchbot-tag

**Comment by Maikeleg** [comment]
Thanks for replying me so quick and for the answer. Pity it’s working like that
Thanks for all your work
