### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by pax2011** [devWaves/SwitchBot-MQTT-BLE-ESP32#108]
Keep getting
{"id":"switchbotone","status":"errorLocatingDevice"} The MAC address is correct. What can I try?

**Comment by devWaves** [comment]
you will need to post your config changes or message me on HA forum or reddit with them. Also it needs to be switchbot branded, not "magic switchbot"

**Comment by pax2011** [comment]
I deleted switchbot HA integration and now everything is working!
