### ISSUE TITLE
Can't control the Plug Mini. Serial log: Failed to connect, deleted client

### ISSUE THREAD

**Issue by tobernguyen** [devWaves/SwitchBot-MQTT-BLE-ESP32#115]
Hi,

I followed all the instructions and used PlatformIO to flash to ESP32. I got the Plug Mini to appear in HA. But I couldn't control (turn on/off) the plug. My ESP chip is is ESP-WROOM-32.
![image](https://user-images.githubusercontent.com/10015525/204637342-f5f0e1f4-0c16-4c96-befa-9a4757d4e98b.png)

I set the `printSerialOutputForDebugging` to `true` to debug. When I send a command from HA (eg, turn off the plug). These logs get printed out constantly

```
Device: 
big_monitor
Device value: 
OFF
Try to connect. Try a reconnect first...
New client created
lld_pdu_get_tx_flush_nb HCI packet count mismatch (1, 2)
Failed to connect, deleted client
Try to connect. Try a reconnect first...
New client created
Failed to connect, deleted client
Try to connect. Try a reconnect first...
New client created
Failed to connect, deleted client
Try to connect. Try a reconnect first...
New client created
Failed to connect, deleted client
Try to connect. Try a reconnect first...
New client created
lld_pdu_get_tx_flush_nb HCI packet count mismatch (1, 2)
Failed to connect, deleted client
Try to connect. Try a reconnect first...
New client created
lld_pdu_get_tx_flush_nb HCI packet count mismatch (1, 2)
Failed to connect, deleted client
Try to connect. Try a reconnect first...
```

So I'm guessing this is a problem with connecting to the plug via bluetooth? The plug firmware is v1.5

**Comment by devWaves** [comment]
do u have the first version of the plug ( no homekit support) or the newer one that has homekit support? 

mine is the 1st version and seems to work fine
