### ISSUE TITLE
Firmware update curtain

### ISSUE THREAD

**Issue by Capusjon** [devWaves/SwitchBot-MQTT-BLE-ESP32#119]
There seems to be a firmware update for the switchbot curtain. (See screenshot)

Is it safe to proceed with the update or should we withhold updating the curtain bots?

Kund regards
Colin
![Screenshot_20230312_141759_SwitchBot](https://user-images.githubusercontent.com/21157144/224547304-b005b626-0d53-444a-b82b-dee63b207c4d.jpg)

**Comment by ReGGaeGaNdi** [comment]
Hi Colin
I'm using firmware version 6.0 since a while already and everything still is working fine, so I think you also should be able to upgrade without issues.
Regards GaNdi

**Comment by devWaves** [comment]
Yes v6.0 for curtain should work

**Comment by Capusjon** [comment]
Thanks for the response!

**Comment by aptalca** [comment]
Was the firmware pulled? I did get the notice for the v6 upgrade being available and I decided not to do it until I got confirmation here.

Now the switchbot app no longer shows me the v6 upgrade as available 😕
