### ISSUE TITLE
Curtain firmware v6.3 safe to update?

### ISSUE THREAD

**Issue by aptalca** [devWaves/SwitchBot-MQTT-BLE-ESP32#130]
I got a notification for an update to firmware v6.3 on my curtain. Does anyone know if it works with this project? I'm currently on v4.6.

Thanks

**Comment by NSF12345** [comment]
I was running 6.0 for a while, and upgraded to 6.3 the other day. No issues for me. Admittedly, I rarely trigger the curtains manually, usually through automations.
Running SwitchBot ESP32 MQTT version: v7.1

(edited for clarity)

**Comment by aptalca** [comment]
Thanks for the confirmation. I went ahead and updated to 6.3 and all is well with ESP32 control
