### ISSUE TITLE
Flash an Smartsocket

### ISSUE THREAD

**Issue by cpeuschel** [devWaves/SwitchBot-MQTT-BLE-ESP32#18]
Hi, 

is it possible to flash an socket with your firmware (e.g. [Smartplug](https://www.amazon.de/DeLock-Steckdosen-Schalter-Energie%C3%BCberwachung-vorinstalliert/dp/B08C6KZFZK/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=delock&qid=1625941339&s=computers&sr=1-3)) to power up the ESP and use the socket as normal?

**Comment by devWaves** [comment]
no probably not

most esp that comes with sockets are not esp32. ESP32 is required for bluetooth

if the socket had ESP32 you could technically load this code on it, but u will lose plug functionality. modifications to the code would be needed for plug functionality and I don't plan on making those kinds of changes
