### ISSUE TITLE
Problem with removed devices

### ISSUE THREAD

**Issue by marithpl** [devWaves/SwitchBot-MQTT-BLE-ESP32#21]
I’ve got a problem with showing switchbot devices in HA. 

By mistake I removed a switchbot devices from HA. I changed a config of SwitchBot MQTT but still there is no devices showing in HA. 

How to “reset” ESP to show devices in HA?

**Comment by devWaves** [comment]
when the esp32 reboots it sends the mqtt discovery info. your devices will automatically create when the esp32 reboots. if it does not that is an issue with your HA.

ensure the device is fully deleted, then reboot the esp32

**Comment by marithpl** [comment]
How to ensure the device is fully deleted?

**Comment by devWaves** [comment]
Configurations->Devices

if the switchbot is in the list, click it and select delete

**Comment by marithpl** [comment]
I've deleted this way.
And now MQTT do not discovery again switchbot's.

I tried to remove MQTT integration an add a new one. My tasmotas devices showed up again but switchbot not.

In MQTT Explorer I can find switchbots curtains:
<img width="337" alt="image" src="https://user-images.githubusercontent.com/25366097/127049975-e878107b-8533-42d3-9d4e-b18b4e2fe707.png">

**Comment by devWaves** [comment]
hmm... not sure
I've done it many many times, no issues. but with bots. it should work the same for curtain though.
let me google a little bit...

**Comment by devWaves** [comment]
can u try with short names? maybe the discovery msgs are failing with long names. just for testing, make the names short and see if devices are discovered

**Comment by devWaves** [comment]
oh... you have spaces in the names. I think thats it

**Comment by marithpl** [comment]
I will check in the morning

**Comment by marithpl** [comment]
Now is working. 

Thanks!
