### ISSUE TITLE
Integrate in esphome label:enhancement 

### ISSUE THREAD

**Issue by Metus88** [devWaves/SwitchBot-MQTT-BLE-ESP32#23]
Great job! I would like if it's possible cooperate with esphome to integrate it.
I have a eps32 and I would configure it not only for "SwitchBot-MQTT-BLE-ESP32" but olso for other devices.
Esphome community has already asked to integrate it ( [see here](https://github.com/esphome/feature-requests/issues/454) ).
Thanks

**Comment by devWaves** [comment]
Hey thanks. This component can't be integrated directly with ESPHome but it can be used as a reference. I am on the HA forum also if there are questions
