### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by thematrixdev** [devWaves/SwitchBot-MQTT-BLE-ESP32#32]
> Traceback (most recent call last):
  File "/home/y2kbug/.arduino15/packages/esp32/tools/esptool_py/3.0.0/esptool.py", line 38, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'
exit status 1
Error compiling for board NodeMCU-32S.

**Comment by Jacksonbm1** [comment]
What exactly solved this? I'm trying to figure it out.

**Comment by thematrixdev** [comment]
> What exactly solved this? I'm trying to figure it out.

I have forgotten. Please try:
```
pip3 install pyserial
```

**Comment by Jacksonbm1** [comment]
I solved my issue (might have been different than yours): https://randomnerdtutorials.com/solved-failed-to-connect-to-esp32-timed-out-waiting-for-packet-header/

Basically, it was throwing tons of errors, but the important was that I either needed to hold the boot button down or connect a capacitor between the gnd and en pins to allow it to receive data properly.
