### ISSUE TITLE
Infrared support

### ISSUE THREAD

**Issue by thematrixdev** [devWaves/SwitchBot-MQTT-BLE-ESP32#33]
Is it possible to support infrared via Switchbot hub?
Thanks.

**Comment by devWaves** [comment]
probably not. Switchbot also hasn't released any documentation for local communication with the Switchbot hub. It all uses their API through cloud

This only works for Bluetooth BLE switchbot devices. My guess is the hub only uses WIFI? not sure, I don't own one

I personally use a Broadlink RM Pro+ for IR and RF and it has been flawless once I enabled local control for it. I know that doesn't help though if you already have the Switchbot hub
