### ISSUE TITLE
Contact/Motion sensor configuration

### ISSUE THREAD

**Issue by MostHated** [devWaves/SwitchBot-MQTT-BLE-ESP32#36]
You will have to forgive me, this is my first time dealing with Switchbot as well as ESP32 devices. I just got this device (https://www.amazon.com/dp/B094XZ8H5H?psc=1&ref=ppx_yo2_dt_b_product_details) which is a contact sensor, but also a motion sensor with a button. For the configuration, do I put the mac address in both the contact sensor as well as a motion sensor, or just the contact sensor?

Thanks,
-MH

**Comment by devWaves** [comment]
switchbot sells 2 different devices. only put the mac in one list. put yours in the contact list only

**Comment by MostHated** [comment]
Much appreciated, looks like all is working well.
