### ISSUE TITLE
spaces in names of devices don't register in HA, use _ instead

### ISSUE THREAD

**Issue by mclever** [devWaves/SwitchBot-MQTT-BLE-ESP32#40]
When you use a space in the name of a device it doesn't register in HA, use _ instead. Shows up in MQTT fine, just doesn't show up as a device in HA.

**Comment by chvvkumar** [comment]
Ha! I just found this out from this comment. I was banging my head against the wall for a couple of hours:

https://github.com/devWaves/SwitchBot-MQTT-BLE-ESP32/issues/21#issuecomment-887052538

**Comment by devWaves** [comment]
ya I will put in a change to remove spaces or add a comment. thx

**Comment by devWaves** [comment]
latest version 6.5 should replace all spaces with _ underscore if used in names
