### ISSUE TITLE
ESP8266 support?

### ISSUE THREAD

**Issue by broyuken** [devWaves/SwitchBot-MQTT-BLE-ESP32#43]
Is there any way you could make this support ESP8266 as well? I'm specifically looking at using a D1 mini pro.

**Comment by iMicknl** [comment]
@broyuken does the D1 mini pro support bluetooth (LE)? This is a requirement since this code (SwitchBot MQTT) communicates via Bluetooth LE with the devices.

I assume that that is the reason why ESP8266 isn't supported.

**Comment by broyuken** [comment]
ah that might be the issue now that you mention that. I think I ran into something similar when I was trying to use this for miflora.
