### ISSUE TITLE
HA sees the devices but wont operate them

### ISSUE THREAD

**Issue by pprobbins** [devWaves/SwitchBot-MQTT-BLE-ESP32#45]
Hi, I have  problem. I set up the esp32 with HA and the switchbot code and everything ran great for weeks. Then around the time Switchbot released their hub firmware update but the HA integration stopped responding. I updated the firmware but still nothing, I then update the esp32 to Switchbot code v6.5 and it started working. But it has gone back to not responding. It shows the devices but when I try and click to turn on a device it doesn't do anything. It is also stating the curtains are closed but they are open.

https://user-images.githubusercontent.com/91563437/146672951-e5a4225c-d151-4f03-bc33-80f9def1ceb6.mp4

**Comment by devWaves** [comment]
Can your device be controlled with just your phone and the app? unplug the switchbot hub for now, it is not used at all for this

curtains need to be calibrated to work with the esp32. The switchbot hub may have reset them or something

You should browse MQTT and see what messages are showing up
