### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by samip5** [devWaves/SwitchBot-MQTT-BLE-ESP32#47]
It would be really nice if this could be be implemented in a way that enables me to connect to an IPv6-only MQTT broker.

Example on IPv6 support on ESP8266: https://github.com/IPv6-ESP8266/IPv6-ESP8266

**Comment by devWaves** [comment]
I don't think this is possible yet with esp32 arduino https://github.com/espressif/arduino-esp32/issues/1261

**Comment by samip5** [comment]
> I don't think this is possible yet with esp32 arduino https://github.com/espressif/arduino-esp32/issues/1261

It is possible with SLAAC addresses.

**Comment by devWaves** [comment]
the EspMQTTClient doesn't look like it is setup for ipv6. I will close issue but will reopen if needed
