### ISSUE TITLE
Could the comfortably data be got from meter-plus?

### ISSUE THREAD

**Issue by thematrixdev** [devWaves/SwitchBot-MQTT-BLE-ESP32#58]
Thanks.

**Comment by devWaves** [comment]
not yet. The meter plus data is slightly different than the standard meter, and I just got lucky that my code needed minimal changes to support it. If "comfortably data" is available it is not in the broadcasted data, it would require connecting to the meter plus like the code does to retrieve bot firmware value etc

the documentation available has nothing specific for meter plus yet, only regular meter github.com/OpenWonderLabs/python-host/wiki/Meter-BLE-open-API

cheers
