### ISSUE TITLE
NimBLE 1.3.8 and 1.4.0 breaks functionality

### ISSUE THREAD

**Issue by devWaves** [devWaves/SwitchBot-MQTT-BLE-ESP32#64]
I just found out that when installing NimBLE 1.3.8 it breaks stuff. Not sure what the issue is but stick with 1.3.7 for now

the issue remains with NimBLE 1.4.0

the issue that you will notice is the first command sent to the switchbot works, but then the esp32 stops responding after that. Only the first command will work with version 1.3.8 and above

**Comment by Jaxom99** [comment]
Thanks for notifiying this, I found myself in the same situation. 
Did you open a ticket on their side ? Like in this repo perhaps : https://github.com/h2zero/NimBLE-Arduino

**Comment by devWaves** [comment]
@Jaxom99 I haven't had the chance to look if I can fix it from my end yet. I was going to do that once I had more info to provide or some sample basic code to simulate the issue. To reproduce thr issue with current code, they would need switchbot devices

**Comment by devWaves** [comment]
I've got a fix for the NimBLE issues. I will release a v6.12 with the fix. Just want to test a bit more

**Comment by devWaves** [comment]
v6.12 released and solves the NimBLE v1.3.8, v1.4.0 issues

**Comment by Jaxom99** [comment]
thanks, I will test it soon as well!
