### ISSUE TITLE
Power led off (please)

### ISSUE THREAD

**Issue by pickonedev** [devWaves/SwitchBot-MQTT-BLE-ESP32#66]
Hi!

There is any way to turn off the power led of my esp32 board? It is very powerful and annoying. There is no setting into the interface UI... I can only do firmware update.

Thank you in advace!

**Comment by devWaves** [comment]
Hey. On some esp32 there are 2 LEDs. The power LED and the LED linked to a GPIO pin

the power LED cannot be turned off for most esp32. The only way to turn it off is to physically remove the led

the gpio LED can be enable/disabled with thesr settings

```
static const bool ledOnBootScan = true;              // Turn on LED during initial boot scan
static const bool ledOnScan = true;                  // Turn on LED while scanning (non-boot)
static const bool ledOnCommand = true;               // Turn on LED while MQTT command is processing. If scanning, LED will blink after scan completes. You may not notice it, there is no delay after scan
```
