### ISSUE TITLE
errorConnect with switchbots bot

### ISSUE THREAD

**Issue by baty0man** [devWaves/SwitchBot-MQTT-BLE-ESP32#67]
Hi,

I'm pretty new with MTQQ,. I've set up the ESP32 board and it can read the battery of my switchbot bots successfully and the entities appear on HA. However when I toggle the switch ion HA it doesn't do anything. Looking at the messages on the status topic i get the following:

{"status":"errorConnect","command":"OFF"}

Not sure what I'm doing wrong, any help would be appreciated.

Thanks

**Comment by devWaves** [comment]
Is your esp32 close enough to the bot? what is the linkquality rssi value that shows in HA?

**Comment by baty0man** [comment]
Sorry for the late reply, the esp32 board is about a meter away from the bots.
![Screenshot 2022-05-09 081917](https://user-images.githubusercontent.com/64519121/167318095-080781b7-a7ef-4a70-882e-47d45d834c3b.png)

**Comment by devWaves** [comment]
I have just made updates to a v7.0-preRelease here
https://github.com/devWaves/SwitchBot-MQTT-BLE-ESP32/tree/v7alpha

Can you try the v7.0-preRelease and let me know if you still have issues?

just ignore the new settings related to "mesh"

**Comment by baty0man** [comment]
Still the same issue unfortunately. I've deleted all topics and HA entities, uploaded the new version. I can see the new entities on HA but when I press the switch button, nothing happens:
![image](https://user-images.githubusercontent.com/64519121/167987824-bef8b730-7387-41da-9dd8-e8f222d6e246.png)

**Comment by devWaves** [comment]
hmm.. nothing stands out. device names look fine. I can see the guestroom bot worked to request settings, but not livingroom bot

Are any other bluetooth things trying to connect to the bots like switchbot hub etc? Maybe try taking a bot battery out, put it back then turn on the esp32

I am running firmware 6.2 for bots, but 4.9 is fine also

I can try with your device names later, but it should work

**Comment by Jacksonbm1** [comment]
I also have been trying to use the switchbot bots. They are autodiscovered by homeassistant, but controlling them seems like it's not working. I'm not super familiar with homeassistant or MQTT, so this might be tough for me to help you debug, but lmk what would be helpful. I've treid removing the battery and putting it back in. I do have other devices attempting to connect, but since it receives BLE commands, shouldn't it not matter?

**Comment by Jacksonbm1** [comment]
Also, when I flip the switch on homeassistant, it looks like it's trying to push a new attribute in the JSON: 

![image](https://user-images.githubusercontent.com/39594156/171545319-ccb4b725-ed43-4fea-a2ae-b61f6032ce1f.png)

note that in the "Desk_up" section, I've pressed the homeassitant button and it's added a "set = ON" to the MQTT explorer output

**Comment by Jacksonbm1** [comment]
Update it was: https://github.com/devWaves/SwitchBot-MQTT-BLE-ESP32/issues/64

**Comment by devWaves** [comment]
@baty0man is it still giving you issues?  Are you using NimBLE v 1.3.7 as mentioned? There is a known issue when using v1.3.8

**Comment by devWaves** [comment]
Closing this as I believe NimBLE v1.3.7 solves it. Can be reopened if still an issue
