### ISSUE TITLE
Switchbot Bot connection problem

### ISSUE THREAD

**Issue by alexanderroese** [devWaves/SwitchBot-MQTT-BLE-ESP32#71]
Hi,

I have bought a Switchbot Bot. Via the APP I have read the Bluetooth MAC of the bot and entered it in the Arduino allBots list. Unfortunately I have the problem that in the HomeAssistant no entity is created for the bot.

`/* Switchbot Bot Settings */
static std::map<std::string, std::string> allBots = {
  { "switchbotone", "dc:23:4d:7f:11:07" }
};`

I have already tested the following versions v6.10, v6.9 and v7.0-preRelease.

Is it necessary to bring the bot into a certain state so that the ESP32 can query data? With the setting `printSerialOutputForDebugging = true` I only get the following debug message 
`Advertised Device found: Name: TY, Address: dc:23:4d:7f:11:07, manufacturer data: d007000300000100e7ec75105b8057aa19ee8cc9db80fbdf, serviceUUID: 0xa201
Service Data:
UUID: 0xa201, Data: `

 
I have used the following libraries

- NimBLEDevice Version 1.3.7 (Due to the problem in the 1.3.8 changed to the 1.3.7)
- EspMQTTClient Version 1.13.3
- ArduinoJson Version 6.19.4
- CRC32 Version 2.0.0
- ArduinoQueue Version 1.2.5

The connection to MQTT and HomeAssistant work, as I can see that it has created entries using the MQTT Explorer. In HomeAssistant it also created an entity when I set an entry for another sensor type. The only data created in MQTT by the Esp32 is the linkqualtity (rssi = -67) of the esp32, the lastwill status (lastwill = online) and the status of the esp32 itself which is set to scanning (`{"status": "scanning"}`).

I think it might be a problem from my side because my purchased version is not the original from switchbot and I think the protocol is different because he is from Luminea brand.

**Comment by devWaves** [comment]
ya you must have a different brand. This code only works with the SwitchBot brand

the advertisded data should look like this for a bot
```
Advertised Device found:
Name: , Address: xx:xx:xx:xx:xx:xx, manufacturer data: 5900xxxxxxxxxxxx, serviceUUID: cba20d00-224d-11e6-9fb8-0002a5d5c51b
```
