### ISSUE TITLE
Web UI for adding/remove devices?

### ISSUE THREAD

**Issue by fabiosoft** [devWaves/SwitchBot-MQTT-BLE-ESP32#72]
Any plan to add a new device from a web gui? 

Something to avoid always connect esp32 to my computer and recompile the binary everytime I buy a new switchbot device

PS: Amazing work,

**Comment by devWaves** [comment]
Hey, I wasn't really planning on adding the option to add devices from a web GUI . I would have to change how variables are stored etc

but the options to update OTA is already there so you don't have to plug the esp32 into the PC everytime, just the first time. Just upload the compiled .bin file using the esp32 ip address in a web browser
