### ISSUE TITLE
no SwitchBot action from HA triggers

### ISSUE THREAD

**Issue by m3obsessed** [devWaves/SwitchBot-MQTT-BLE-ESP32#73]
@devWaves
Please help!  But first some context.  I have had 4 switchbots in HA, thanks to the Switchbot integration.  As I continue to have issues (i.e., sensors often unavailable), I decided to try the Switchbot-MQTT-BLE-ESP32 route.  No issue downloading the code, editing for wifi, MQTT user name, etc... compiling and uploading to my D1 Mini.  I can see all 4 switchbots with MQTT explorer.  And I do see them within the MQTT Integration within in HA - see below.

<img width="1017" alt="Screen Shot 2022-06-01 at 3 11 20 PM" src="https://user-images.githubusercontent.com/68436997/171425132-24b93fbd-2642-46f3-816a-bf27c27ef328.png">

When I select one of the sensors (blinds_down), I can see all the right entities.

<img width="1012" alt="Screen Shot 2022-06-01 at 3 13 13 PM" src="https://user-images.githubusercontent.com/68436997/171425529-e45a3cc2-ebdf-4b2e-bdc6-47152ea38341.png">

Unfortunately, when I try to activate the switchbot by pressing the switch, nothing happens with the Switchbot.
   
<img width="857" alt="Screen Shot 2022-06-01 at 3 14 28 PM" src="https://user-images.githubusercontent.com/68436997/171425766-2d2fe505-94e5-4a27-84cc-051fd335ad6b.png">

Honestly, I am lost (and stuck).  Not sure what to do....  Any ideas?
Thanks in advance for any help/perspective you can provide.
Gerard

**Comment by devWaves** [comment]
Are you using v1.3.8 of NimBLE library? if so switch to v1.3.7. Something changed in 1.3.8 that broke stuff

If you watch the main MQTT topic it should give you some info of whats happening. If u can provide some MQTT messages it will say if it failed or success

**Comment by m3obsessed** [comment]
Thanks for getting back to me so quickly.  I was using v1.3.8 of NimBLE library.  I switched to v1.3.7.  Recompiled and re-uploaded to my D1 Mini ESP32.  Still no action from the switchbot when I turn it on/off within HA.
How would you suggest I watch the main MQTT topic such that I can share some of the MQTT messages (sorry - this is beyond my current knowledge/capability)?
Gerard

**Comment by m3obsessed** [comment]
@devWaves From within Home Assistant / MQTT Integration, I listened to Topic:  switchbot/D1_Mini_esp32/bot/Blinds_Stop/set

I activated the switch button three times.  No action from the bot.  But this is what I got:
<img width="502" alt="Screen Shot 2022-06-02 at 2 48 54 PM" src="https://user-images.githubusercontent.com/68436997/171644328-becaa6f9-27c3-48d5-9428-1f5181b709cb.png">
 
Gerard

**Comment by devWaves** [comment]
If you are using MQTTExplorer it is easy to see the MQTT traffic as it goes by

The set message would be sent by HA to the MQTT broker, so even with the ESP32 off you would see that. You would want to find a message sent by the ESP32 to diagnose more (or you can also plug it into your PC and use serial monitor to watch the logs)

As soon as a set message is received you should see the main MQTT topic  (for you ```switchbot/D1_Mini_esp32```) show ```{"status":"controlling"}```. This means the ESP32 received the command and is trying to process it

Once the ESP32 receives the command you should see messages on the device topic ```switchbot/D1_Mini_esp32/bot/Blinds_Stop/status```  that will have messages similar to this ....

```
Example payload:
                      - {"status":"connected", "command":"ON"}
                      - {"status":"errorConnect", "command":"ON"}
                      - {"status":"errorCommand", "command":"NOTVALID"}
                      - {"status":"commandSent", "command":"ON"}
                      - {"status":"busy", "value":3, "command":"ON"}
                      - {"status":"failed", "value":9, "command":"ON"}
                      - {"status":"success", "value":1, "command":"ON"}
                      - {"status":"success", "value":5, "command":"PRESS"}
                      ```

If none of those messages are displayed then the issue might be that the ESP32 can't read/subscribe to the set topic? 
Are you using an MQTT user/password that is used by other stuff? Maybe create a unique MQTT user for the ESP32. Someone else mentioned they had issues sharing MQTT userIds

**Comment by m3obsessed** [comment]
@devWaves 
Thank you for your guidance.  So I looked at the main MQTT topic "switchbot/D1_Mini_esp32".  It showed either "scanning" or "idle".  I looked at the history, that is all I could see.
<img width="1021" alt="Screen Shot 2022-06-06 at 2 42 13 PM" src="https://user-images.githubusercontent.com/68436997/172173460-00b01344-f122-48d4-8396-416916cbfe5d.png">
 
Then I noticed that the signal was not as high as what you had recommended.  So I moved the ESP32 close to the Raspberry Pi running HA and the four Switchbots.  Left it unplugged while I deleted all Switchbot devices in HA, and deleted all the ESP32-related topics in MQTT Explorer.  

I then plugged the D1 Mini back in.  Let MQT rediscover them.  Went to MQTT Explorer....  AND MAGIC!!!!
<img width="683" alt="Screen Shot 2022-06-06 at 3 53 54 PM" src="https://user-images.githubusercontent.com/68436997/172186207-ac429946-2890-428a-8ce5-f83e2b3ac3c7.png">

ESP32 is controlling.  All four Switchbots are showing "success".  I tried them all from within HA and they all work.

At the end, doing some cleanup, moving the ESP32 closer to the Switchbots did the trick.  

Anyway, thank you SO MUCH for your help.  I learned a few things about MQTT Explorer in the process.  And THANK YOU for making this really cool integration between Switchbot and HA via ESP32....  Really cool stuff.

Gerard

**Comment by devWaves** [comment]
awesome glad you got it working. Just a npte that it doesnt really matter how close the esp32 is to the RPi, just needs to be close to the switchbots. The wifi signal can work from really far away, it os the bluetooth signal that needs to be good

have a good one, I will close the issue
