### ISSUE TITLE
Switchbot Lock support?

### ISSUE THREAD

**Issue by 1liminal1** [devWaves/SwitchBot-MQTT-BLE-ESP32#74]
Hey mate, 

Hope you're well :)

Will you be supporting the lock and if so, when-ish?

**Comment by devWaves** [comment]
Hey. So I don't own a lock so I can't reverse engineer it. It also is not documented yet
https://github.com/OpenWonderLabs/SwitchBotAPI-BLE

There are ways to reverse engineer BLE commands with android but I can't go that route without one

Being a lock it might have encryption added, not sure

We can reopen this if more lock info is available
