### ISSUE TITLE
Pan/Tild Cam support?

### ISSUE THREAD

**Issue by BangerTech** [devWaves/SwitchBot-MQTT-BLE-ESP32#77]
Hey there ;-)
do you think it would be possible to add a SwitchBot Pan/Tild Cam support? Of course i´m willing to debug again ;-)

greets

**Comment by devWaves** [comment]
Hey @BangerTech just closing the issue for now. Can be reopened if more info is provided and/or if someone can confirm cameras support some BLE functions
