### ISSUE TITLE
Not controlling switchbot 

### ISSUE THREAD

**Issue by Danny2100** [devWaves/SwitchBot-MQTT-BLE-ESP32#81]
On switchbot firmware 5.0 and now on 6.3 after startup when sending commands on or off by tapping the switch nothing happens it just reverts back to off and then within a few minutes becomes unavailable.

It connects to the switchbot as I can't use the app to control it meaning it's already connected to another device.

I'm using an esp32 wemos d1 mini.

I rebooted, got it to "turn on" the command worked and now it won't go back to off.

I also tried using button mode but that didn't seem to change the behavior.

Any ideas?

**Comment by devWaves** [comment]
most likely this https://github.com/devWaves/SwitchBot-MQTT-BLE-ESP32/issues/64

needs version 1.3.7 NimBLE atm

**Comment by devWaves** [comment]
@Danny2100 Just closing this issue as I believe NimBLE 1.3.7 fixes it. Just reopen if you still are having issues. Leave a comment if you can confirm you got it working please
