### ISSUE TITLE
bot is not recognized

### ISSUE THREAD

**Issue by GiladShoham** [devWaves/SwitchBot-MQTT-BLE-ESP32#88]
I was able to flash everything correctly, and I see the hub in mqtt explorer (see image)
<img width="841" alt="image" src="https://user-images.githubusercontent.com/3840769/180483191-11851d1f-bbaf-42db-8b08-888b512a80d6.png">

This is the value of the config message
```js
{
  "~": "switchbot/esp32_switch_bot_hub/esp32",
  "name": "esp32_switch_bot_hub Linkquality",
  "device": {
    "identifiers": [
      "switchbotesp_esp32_switch_bot_hub_MAC_ADD"
    ],
    "manufacturer": "WonderLabs SwitchBot",
    "model": "ESP32",
    "name": "esp32_switch_bot_hub"
  },
  "avty_t": "switchbot/esp32_switch_bot_hub/lastwill",
  "uniq_id": "switchbotesp_esp32_switch_bot_hub_MAC_ADD_linkquality",
  "stat_t": "~/rssi",
  "icon": "mdi:signal",
  "unit_of_meas": "rssi"
}
```

But I'm not able to recognize my bot.
Here is an image of the esp32 on both sides + the bot
In case it's hard to read, it says `ESP WROOM 32D`
This is what I bought from aliexpress - https://www.aliexpress.com/item/1005001636295529.html?spm=a2g0o.order_list.0.0.70001802UZ4iV4
![IMG_8078](https://user-images.githubusercontent.com/3840769/180483997-bff9a7a4-7e0c-4c5c-a64c-bf64614d0c1c.jpeg)
![IMG_8079](https://user-images.githubusercontent.com/3840769/180484327-74d3ffa5-bc29-45af-9793-adf7fca51718.jpeg)

Maybe it's my device that is not supported? or did I use the wrong version? or do I need to send some command to find the bot?

Thanks a lot!

**Comment by devWaves** [comment]
I think someone mentioned using an ESP32 devkit v4 with ESP WROOM 32D but I would have to check through the HA forum chats

did you uncomment the part inside the bot list? the default code looks like this

```
static std::map<std::string, std::string> allBots = {
  /*{ "switchbotone", "xX:xX:xX:xX:xX:xX" },
    { "switchbottwo", "yY:yY:yY:yY:yY:yY" }*/
};
```

when you add a bot it should look like this with the inside uncommented

```
static std::map<std::string, std::string> allBots = {
  { "switchbotone", "xX:xX:xX:xX:xX:xX" }
};
```

**Comment by GiladShoham** [comment]
No, I missed this part. I'll try it soon and will update here about it:)

**Comment by GiladShoham** [comment]
@devWaves Works like a charm now
see the attached video - https://youtu.be/cxfHDoZxu54

Thanks for your help!
