### ISSUE TITLE
Update to the latest version

### ISSUE THREAD

**Issue by smartmatic** [devWaves/SwitchBot-MQTT-BLE-ESP32#89]
Hi,

first of all thank you for that great project. I want to update from my current installed version 6.10 to the latest release.

How is the simpelst and fastest way to do it? It‘s not fully clear for me. Is there a way to automatically upgrade to the latest release via a kind of button or is it manually work?

I would do it the following steps
1. Download latest release 6.11
2. Copy my settings from current installed version 6.10 to new releasse
3. Compile a bin file
4. Upload the file via Web GUI

Are those steps the needed and right steps?

**Comment by devWaves** [comment]
yes those are the correct steps
